name: publish site
on: # 在什么时候触发工作流
  push: # 在从本地main分支被push到GitHub仓库时
    branches:
      - main
  pull_request: # 在main分支合并别人提的pr时
    branches:
      - main
jobs: # 工作流的具体内容
  deploy:
    runs-on: ubuntu-22.04 # 创建一个新的云端虚拟机 使用最新Ubuntu系统
    steps:
      - uses: actions/checkout@v3 # 先checkout到main分支
        with: 
          fetch-depth: 0
      - name: set up python 
        uses: actions/setup-python@v4 # 再安装Python3和相关环境
        with:
          python-version: 3.11
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material      
      - name: gh-deploy
        run : |
          mkdocs build          
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'deploy'
          mkdocs gh-deploy 
      - name: 推送更改
        uses:  ad-m/github-push-action@master
        with:
          force_with_lease: true
      - name: mkdocs build
        run: mkdocs build --clean --strict